services:
  - type: web
    name: spendwise-api
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=60.0 -XX:InitialRAMPercentage=20.0
